### ISSUE TITLE
Bug with server join message

### ISSUE THREAD

**Issue by RDIL** [cakebotpro/cakebot#39]
Just noticed that in the logs, the following is thrown:
```python
Jun 25 14:26:01 Ignoring exception in on_guild_join
Jun 25 14:26:01 Traceback (most recent call last):
Jun 25 14:26:01   File "/home/jumbocakeyumyum/.local/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
Jun 25 14:26:01     await coro(*args, **kwargs)
Jun 25 14:26:01   File "main.py", line 205, in on_guild_join
Jun 25 14:26:01     await ServerUtil.get_general(guild).send_message(embed=EmbedUtil.prep(title="Heya!", description="Today is a great day, because I get the honor of joining this server :D"))
Jun 25 14:26:01 AttributeError: 'NoneType' object has no attribute 'send_message'
```

Can somebody take a look into this please

Ignore the times being wrong

**Comment by RDIL** [comment]
Should be fixed now.  Will continue to monitor.
